version: '3.5'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.1
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    container_name: traefik
    restart: always
    depends_on:
      - nginx
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
      - "3306:3306"
      - "6379:6379"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal
      - proxy

  nginx:
    image: nginx
    labels:
      - traefik.http.routers.nginx.rule=Host(`pharmaglobe.loc`)
    depends_on:
      - php
    volumes:
      - D:\openserver\OSPanel\domains\pharmaglobe.loc\.docker\nginx\conf.d\default.nginx:/etc/nginx/conf.d/default.conf
      - D:\openserver\OSPanel\domains\pharmaglobe.loc:/var/www/html
    networks:
      - internal

  php:
    image: myphp
    volumes:
      - D:\openserver\OSPanel\domains\pharmaglobe.loc\.docker\php\php.ini:/usr/local/etc/php/php.ini
      - D:\openserver\OSPanel\domains\pharmaglobe.loc:/var/www/html
    networks:
      - internal

  mysql:
    image: mysql
    ports:
    - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: SomeRootPassword1!
        MYSQL_USER: laravel
        MYSQL_PASSWORD: laravel
        MYSQL_DATABASE: laravel
    volumes:
        - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - internal

networks:
  proxy:
  internal: