version: '3.5'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.1
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.mysql.address=:3306"
      - "--entrypoints.nginx.address=:80"
    container_name: traefik
    restart: always
    # depends_on:
    #   - nginx
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
      - "3306:3306"
      - "6379:6379"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./docker/traefik.yml:/traefik.yml
    networks:
      - internal
      - proxy

  nginx:
    image: nginx
    container_name: nginx
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.http.routers.nginx.rule=Host(`laravel.localhost`)"
    depends_on:
      - php
    volumes:
#      - ./.docker/nginx/default.nginx:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./:/var/www
    networks:
      - internal
      #- proxy

  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    image: laravelphp
    container_name: php
    working_dir: /var/www
    volumes:
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www
    networks:
      - internal


  redis:
    image: 'redis:5.0'
    container_name: redis
    # volumes:
    #   - /data
    ports:
      - 6379
    networks:
      - internal

  mysql:
    image: mysql:5.7
    container_name: mysql
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.mysql.rule=HostSNI(`*`)"
      - "traefik.tcp.services.mysql.loadbalancer.server.port=3306"
      - "traefik.tcp.routers.mysql.entrypoints=mysql"
    environment:
      MYSQL_ROOT_PASSWORD: SomeRootPassword1!
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_DATABASE: laravel
    networks:
      - internal

networks:
  proxy:
  internal: